# =====================================================
# SmartLend - Credit Risk & Loan Portfolio Analytics
# Python Feature Engineering
# =====================================================

In [ ]:
import pandas as pd
import numpy as np
from sqlalchemy import create_engine

In [ ]:
from urllib.parse import quote_plus
from sqlalchemy import create_engine

In [ ]:
# Connect Python to MySQL

username = "root"
password = quote_plus("Karela@_2306")

engine = create_engine(
    f"mysql+pymysql://{username}:{password}@localhost/smartlend"
)

In [ ]:
customers = pd.read_sql(
            "SELECT * FROM customers",
            engine
)

customers.head()

,customer_id,gender,age,marital_status,education,occupation,annual_income,city,state,join_date
0,C00001,Male,37,Married,Master,Business,2853670.0,Ludhiana,Punjab,2020-09-01
1,C00002,Male,65,Single,PhD,Business,1575315.0,Cuttack,Odisha,2025-05-02
2,C00003,Male,60,Single,Bachelor,Government,2781078.0,Bhopal,Madhya Pradesh,2020-03-10
3,C00004,Female,52,Married,Bachelor,Business,1356088.0,Faridabad,Haryana,2025-01-16
4,C00005,Male,44,Married,PhD,Self-Employed,758080.0,Ludhiana,Punjab,2024-11-11

In [ ]:
loans = pd.read_sql(
        " SELECT * FROM loans",
        engine
)

print(loans.shape)

(25000, 9)

In [ ]:
credit_risk = pd.read_sql(
    "SELECT * FROM credit_risk",
    engine
)

print(credit_risk.shape)

(10000, 6)

In [ ]:
df = customers.merge(
    loans,
    on="customer_id",
    how="inner"
)

df = df.merge(
    credit_risk,
    on="customer_id",
    how="inner"
)

In [ ]:
df.shape

(25000, 23)

In [ ]:
df.head()

,customer_id,gender,age,marital_status,education,occupation,annual_income,city,state,join_date,...,interest_rate,loan_type,loan_status,loan_issue_date,loan_end_date,credit_score,debt_to_income_ratio,late_payments,loan_default,risk_category
0,C00002,Male,65,Single,PhD,Business,1575315.0,Cuttack,Odisha,2025-05-02,...,8.60,Credit Line,Active,2023-04-19,2028-03-23,663,0.43,1,0,Medium Risk
1,C00002,Male,65,Single,PhD,Business,1575315.0,Cuttack,Odisha,2025-05-02,...,7.74,Auto Loan,Closed,2021-04-11,2028-03-05,663,0.43,1,0,Medium Risk
2,C00002,Male,65,Single,PhD,Business,1575315.0,Cuttack,Odisha,2025-05-02,...,10.73,Credit Line,Defaulted,2024-08-11,2034-06-20,663,0.43,1,0,Medium Risk
3,C00004,Female,52,Married,Bachelor,Business,1356088.0,Faridabad,Haryana,2025-01-16,...,13.04,Education Loan,Closed,2025-04-15,2030-03-20,559,0.50,1,0,High Risk
4,C00004,Female,52,Married,Bachelor,Business,1356088.0,Faridabad,Haryana,2025-01-16,...,11.83,Auto Loan,Active,2022-07-28,2024-07-17,559,0.50,1,0,High Risk

In [ ]:
df.columns

Index(['customer_id', 'gender', 'age', 'marital_status', 'education',
       'occupation', 'annual_income', 'city', 'state', 'join_date', 'loan_id',
       'loan_amount', 'loan_term_months', 'interest_rate', 'loan_type',
       'loan_status', 'loan_issue_date', 'loan_end_date', 'credit_score',
       'debt_to_income_ratio', 'late_payments', 'loan_default',
       'risk_category'],
      dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   customer_id           25000 non-null  object
 1   gender                25000 non-null  object
 2   age                   25000 non-null  int64
 3   marital_status        25000 non-null  object
 4   education             25000 non-null  object
 5   occupation            25000 non-null  object
 6   annual_income         25000 non-null  float64
 7   city                  25000 non-null  object
 8   state                 25000 non-null  object
 9   join_date             25000 non-null  object
 10  loan_id               25000 non-null  object
 11  loan_amount           25000 non-null  float64
 12  loan_term_months      25000 non-null  int64
 13  interest_rate         25000 non-null  float64
 14  loan_type             25000 non-null  object
 15  loan_status           25000 non-null  object
 16  loan_issue_date       25000 non-null  object
 17  loan_end_date         25000 non-null  object
 18  credit_score          25000 non-null  int64
 19  debt_to_income_ratio  25000 non-null  float64
 20  late_payments         25000 non-null  int64
 21  loan_default          25000 non-null  int64
 22  risk_category         25000 non-null  object
dtypes: float64(4), int64(5), object(14)
memory usage: 4.4+ MB

In [ ]:
df['age'].describe()

count    25000.000000
mean        43.258520
std         12.935154
min         21.000000
25%         32.000000
50%         43.000000
75%         55.000000
max         65.000000
Name: age, dtype: float64

In [ ]:
df['age_group'] = pd.cut(
    df['age'],
    bins=[18,25,35,45,55,100],
    labels=[
        '18-25',
        '26-35',
        '36-45',
        '46-55',
        '56+'
    ]
)

In [ ]:
df[['age','age_group']].head(10)

   age age_group
0   65       56+
1   65       56+
2   65       56+
3   52     46-55
4   52     46-55
5   44     36-45
6   51     46-55
7   51     46-55
8   39     36-45
9   49     46-55

In [ ]:
df['age_group'].value_counts()

age_group
56+      5846
26-35    5655
46-55    5438
36-45    5433
18-25    2628
Name: count, dtype: int64

In [ ]:
df['annual_income'].describe()

count    2.500000e+04
mean     1.625165e+06
std      7.949331e+05
min      2.500690e+05
25%      9.396660e+05
50%      1.622726e+06
75%      2.320543e+06
max      2.999943e+06
Name: annual_income, dtype: float64

In [ ]:
df['income_segment'] = pd.cut(
    df['annual_income'],
    bins= [0,1000000,2000000,3000000],
    labels= [
        'Low Income',
        'Middle Income',
        'High Income'
    ]
)

In [ ]:
df['income_segment'].value_counts()

income_segment
Middle Income    9153
High Income      9068
Low Income       6779
Name: count, dtype: int64

In [ ]:
df['credit_score'].describe()

count    25000.000000
mean       687.472240
std         87.394655
min        334.000000
25%        628.000000
50%        689.000000
75%        749.000000
max        850.000000
Name: credit_score, dtype: float64

In [ ]:
df['risk_category'] = pd.cut(
    df['credit_score'],
    bins= [300,600,750,900],
    labels= [
        'High Risk',
        'Medium Risk',
        'Low Risk'
    ]
)

In [ ]:
df['risk_category'].value_counts()

risk_category
Medium Risk    14780
Low Risk        6125
High Risk       4095
Name: count, dtype: int64

In [ ]:
df['loan_term_months'].describe()

count    25000.000000
mean        89.138400
std         72.473229
min         12.000000
25%         36.000000
50%         60.000000
75%        120.000000
max        240.000000
Name: loan_term_months, dtype: float64

In [ ]:
df['loan_duration_bucket'] = pd.cut(
    df['loan_term_months'],
    bins= [0,24,60,120,300],
    labels= [
        'Short Term',
        'Medium Term',
        'Long Term',
        'Very Long Term'
    ]
)

In [ ]:
df['loan_duration_bucket'].value_counts()

loan_duration_bucket
Medium Term       8353
Long Term         5598
Short Term        5549
Very Long Term    5500
Name: count, dtype: int64

In [ ]:
df[[
    'age',
    'age_group',
    'annual_income',
    'income_segment',
    'credit_score',
    'risk_category',
    'loan_term_months',
    'loan_duration_bucket'
]].head(10)

,age,age_group,annual_income,income_segment,credit_score,risk_category,loan_term_months,loan_duration_bucket
0,65,56+,1575315.0,Middle Income,663,Medium Risk,60,Medium Term
1,65,56+,1575315.0,Middle Income,663,Medium Risk,84,Long Term
2,65,56+,1575315.0,Middle Income,663,Medium Risk,120,Long Term
3,52,46-55,1356088.0,Middle Income,559,High Risk,60,Medium Term
4,52,46-55,1356088.0,Middle Income,559,High Risk,24,Short Term
5,44,36-45,758080.0,Low Income,561,High Risk,48,Medium Term
6,51,46-55,2659034.0,High Income,545,High Risk,180,Very Long Term
7,51,46-55,2659034.0,High Income,545,High Risk,24,Short Term
8,39,36-45,2887878.0,High Income,638,Medium Risk,60,Medium Term
9,49,46-55,1043209.0,Middle Income,653,Medium Risk,60,Medium Term

In [ ]:
df[['age_group',
    'income_segment',
    'risk_category',
    'loan_duration_bucket'
]].isnull().sum()

age_group               0
income_segment          0
risk_category           0
loan_duration_bucket    0
dtype: int64

In [ ]:
df.shape

(25000, 26)

In [ ]:
len(df.columns)

26

In [ ]:
df.columns.tolist()

['customer_id',
 'gender',
 'age',
 'marital_status',
 'education',
 'occupation',
 'annual_income',
 'city',
 'state',
 'join_date',
 'loan_id',
 'loan_amount',
 'loan_term_months',
 'interest_rate',
 'loan_type',
 'loan_status',
 'loan_issue_date',
 'loan_end_date',
 'credit_score',
 'debt_to_income_ratio',
 'late_payments',
 'loan_default',
 'risk_category',
 'age_group',
 'income_segment',
 'loan_duration_bucket']

In [ ]:
df.isnull().sum()

customer_id             0
gender                  0
age                     0
marital_status          0
education               0
occupation              0
annual_income           0
city                    0
state                   0
join_date               0
loan_id                 0
loan_amount             0
loan_term_months        0
interest_rate           0
loan_type               0
loan_status             0
loan_issue_date         0
loan_end_date           0
credit_score            0
debt_to_income_ratio    0
late_payments           0
loan_default            0
risk_category           0
age_group               0
income_segment          0
loan_duration_bucket    0
dtype: int64

In [ ]:
df.shape

(25000, 26)

In [ ]:
# Export Final Dataset

df.to_csv(
    r"E:\Sneh's\Data Science\Projects\12. SmartLend – Credit Risk & Loan Portfolio Analytics\Data\Processed\SmartLend_Analytics_Dataset.csv",
    index=False
)

In [ ]:
# Verify Export

import os

os.path.exists(
    r"E:\Sneh's\Data Science\Projects\12. SmartLend – Credit Risk & Loan Portfolio Analytics\Data\Processed\SmartLend_Analytics_Dataset.csv"
)

True